# Generated by Django 3.0.5 on 2020-04-22 13:47

from django.db import migrations, models
import django.db.models.deletion
import projectapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('date_of_completion', models.DateField(null=True, verbose_name='Дата исполнения')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('images', models.ImageField(blank=True, default=None, null=True, upload_to=projectapp.models.get_image_name, verbose_name='Изображение 550x685')),
                ('main_image', models.BooleanField(default=False, verbose_name='Основная картинка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
