# Generated by Django 3.0.5 on 2020-04-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('PS', 'Дератизация'), ('DF', 'Дезинфекция'), ('PC', 'Дезинсекция'), ('AE', 'Газация')], default='PS', max_length=2, verbose_name='Категория услуги'),
        ),
    ]
