# Generated by Django 3.0.5 on 2020-05-12 12:13

from django.db import migrations, models
import projectapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=projectapp.models.get_image_name, verbose_name='Изображение 370x220'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('PS', 'Дератизация'), ('DF', 'Дезинфекция'), ('PC', 'Дезинсекция'), ('AE', 'Газация'), ('FU', 'Фумигация')], default='PS', max_length=2, verbose_name='Категория услуги'),
        ),
    ]
